### ISSUE TITLE
Object size distribution chart should be more granular

### ISSUE THREAD

**Issue by shapirus** [minio/console#1194]
This is a feature request for a possible improvement of the graphs display page.

In my case almost all objects have size between approximately 40 KB and 200 KB, thus resulting in a nearly useless object size distribution chart:

![distr](https://user-images.githubusercontent.com/725402/140605756-eca98e42-67cf-4641-aadf-dcdf7746e1ae.png)

The ranges should be made more granular, or dynamic, or user-configurable to be useful for cases when the sizes fit a narrow range.

**Comment by harshavardhana** [comment]
> This is a feature request for a possible improvement of the graphs display page.
> 
> In my case almost all objects have size between approximately 40 KB and 200 KB, thus resulting in a nearly useless object size distribution chart:
> 
> ![distr](https://user-images.githubusercontent.com/725402/140605756-eca98e42-67cf-4641-aadf-dcdf7746e1ae.png)
> 
> The ranges should be made more granular, or dynamic, or user-configurable to be useful for cases when the sizes fit a narrow range.

Well we did for generic use cases. It cannot be made more granular since it's captured on server side and persisted on disk.

We won't be able to change data format now. These values are meant for just book keeping. If you want to dig deeper you should setup audit logging to some elk, splunk targets to do further analysis.

Closing this as beyond our scope of what we can do.
