### ISSUE TITLE
Rewind mode does not render folders properly

### ISSUE THREAD

**Issue by adfost** [minio/console#1284]
In rewind mode, all folders are shown from today, even if they were created after the selected time. Also in rewind mode, if the name of a folder is the beginning of the name of another folder (on the same prefix) (i.e. test and test123), test123 and test will appear in test, and test123 will appear in test123.

How to reproduce:
Create a bucket, add objects. Create two folders testfolder1 and testfolder123 in the bucket (both with no prefix). Add objects to them. Then switch to rewind mode.

<img width="1145" alt="Screen Shot 2021-12-02 at 2 22 19 PM" src="https://user-images.githubusercontent.com/15642172/144512731-cde3797f-01f2-4e93-81ba-1d38278f8bcb.png">

**Comment by bexsoft** [comment]
This is expected behavior, correlated with mc and same behavior is visible.



![Image](https://user-images.githubusercontent.com/33497058/207718066-3286796e-3663-4425-8b19-554d356cf768.png)
![Image](https://user-images.githubusercontent.com/33497058/207718064-cd08b0bf-0c66-476f-8da7-abb6d5f7157f.png)
![Image](https://user-images.githubusercontent.com/33497058/207718065-821f393f-27d6-4eae-849a-7509d8e24c12.png)


Closing this issue
