### ISSUE TITLE
Is it possible to upload large objects e.g. 8GB?

### ISSUE THREAD

**Issue by guzman-raphael** [minio/console#1557]
Just a quick question, is it possible to upload large objects such as a 8GB file using the MinIO console browser?

I just gave it a try but received the following message below and saw that it was not inserted in S3. Is it because it would need to perform a multipart upload and that is not implemented yet?

Thanks for the great work! :beers:

Message: `Your proposed upload exceeds the maximum allowed size`

![image](https://user-images.githubusercontent.com/38401847/153630850-1d81ce02-cdfb-4fd0-88f0-9222e690d039.png)

**Comment by harshavardhana** [comment]
You are using AWS S3 as backend here?

**Comment by guzman-raphael** [comment]
@harshavardhana Thanks for the quick reply! Yes, the current setup I have running is the following:
- Image: `minio/minio:RELEASE.2022-02-01T18-00-14Z`
- Command: `minio gateway s3 --console-address ":9001"`
- Gateway is connected to AWS S3

**Comment by harshavardhana** [comment]
> * Docker Image: `minio/minio:RELEASE.2022-02-01T18-00-14Z`
> * Command: `minio gateway s3 --console-address ":9001"`
> * Gateway is connected to AWS S3

So yes we do not support uploading more than 5GiB since AWS S3 will restrict that. You need to use multipart uploads which is rather an expensive memory-heavy operation that we basically avoided in Console UI.

- The best way is do not use S3 Gateway and move to MinIO Server to migrate your data from AWS S3. 
- Or stick to Gateway but use `mc cp` like commands to upload bigger objects than 5GiB
