### ISSUE TITLE
Unable to view user, group, policy, ...

### ISSUE THREAD

**Issue by momiji** [minio/console#1693]
We're using names with "#" character, which is not handled correctly by the console.

Urls generated to view users, groups, policies, and so just append the name without any encoding in the URL, which is problematic when names contain "#" character, as it is recognized by the browser as a hash which is not sent to the server in the request.

Example : https://minio.domain/identity/users/user#1234

Good continuation.

**Comment by bexsoft** [comment]
Issue is not to be present in the latest version of MinIO.

Please feel free to file a new ticket if you think this issue is not solved. Thank you!

<img width="1605" alt="Screen Shot 2022-09-01 at 22 05 28" src="https://user-images.githubusercontent.com/33497058/188050873-0d1c1026-607f-4f6d-a1fd-b57eb4beb733.png">
<img width="1575" alt="Screen Shot 2022-09-01 at 22 05 20" src="https://user-images.githubusercontent.com/33497058/188050878-e723987b-d00a-4ebe-a84d-ab329b279a75.png">
<img width="1580" alt="Screen Shot 2022-09-01 at 22 05 07" src="https://user-images.githubusercontent.com/33497058/188050883-036930ef-019e-42b1-b00f-ba10664041aa.png">
<img width="1588" alt="Screen Shot 2022-09-01 at 22 04 56" src="https://user-images.githubusercontent.com/33497058/188050886-62f37c46-c894-4964-8123-4acd66e2ef11.png">
