### ISSUE TITLE
Token used before issued

### ISSUE THREAD

**Issue by agateaux** [minio/console#2100]
Hello.

I'm getting the same issue as in https://github.com/minio/console/issues/993, but with release RELEASE.2022-06-07T00-33-41Z.
```
API: AssumeRoleWithWebIdentity()
Time: 02:09:08 UTC 06/08/2022
DeploymentID: 74e8d46b-4071-4feb-91f9-c1903a30ce71
RequestID: 16F6832E79EE8CE7
RemoteHost: ******
Host: ******
UserAgent: Go-http-client/1.1
Error: Token used before issued (*jwt.ValidationError)
       5: internal/logger/logger.go:278:logger.LogIf()
       4: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
       3: cmd/sts-handlers.go:372:cmd.(*stsAPIHandlers).AssumeRoleWithSSO()
       2: cmd/sts-handlers.go:523:cmd.(*stsAPIHandlers).AssumeRoleWithWebIdentity()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

I'm running Minio thanks to its Helm chart on Kubernetes, and I use Auth0 plugged on Github as OIDC provider.
I have no way of changing NTP configuration on my Kubernetes cluster or Auth0, as you may know.

**Comment by harshavardhana** [comment]
Fix your time on the host system - NTP needs to be fixed. There is nothing else we can do this is a setup issue @agateaux

**Comment by agateaux** [comment]
I'm sorry but that's not an acceptable answer. I can't ask Auth0 to fix its time. Auth0 works with any other system on my Kubernetes cluster

**Comment by dvaldivia** [comment]
@agateaux but there isn't much we can do to fix time either, the NTP settings are usually handled by the host system not the software that runs on it

**Comment by harshavardhana** [comment]
> I'm sorry but that's not an acceptable answer. I can't ask Auth0 to fix its time. Auth0 works with any other system on my Kubernetes cluster.

You need to fix your local setup - it is not related to Auth0

**Comment by alpeshv** [comment]
@harshavardhana How do you think token authentication on every single app I use, works with the same auth provider and on the same kubernetes cluster, without any extra config, except MinIO?

@agateaux How you found any work around?

**Comment by agateaux** [comment]
> [@harshavardhana](https://github.com/harshavardhana) How do you think token authentication on every single app I use, works with the same auth provider and on the same kubernetes cluster, without any extra config, except MinIO?
> 
> [@agateaux](https://github.com/agateaux) How you found any work around?

@alpeshv 
Well, it was hard, but I reached the infra team of the company I worked for at this time, and asked them to change the time of the machine Kubernetes was installed on. It took a couple of weeks.

**Comment by alpeshv** [comment]
@agateaux Thank you for you reply. 

My keycloak and MinIO are deployed in a two different clusters sitting in completely different regions and there is a time difference of 30 secs. I have migrated to OIDC on keycloak to get skew toleration option in vain. It looks like I have no other options than push for cloak change.

**Comment by ramondeklein** [comment]
OIDC issues claims generally have several timestamps:
- `nbf` specifies from which timestamp the token may be used. Note that this claim is optional.
- `exp` specifies the  timestamp of expiration, so the token isn't valid after this timestamp. This claim is required.
- `iat` specifes the timestamp when the token was issued. It's optional, but most systems do provide it.

So OIDC issued tokens are only valid from `nbf` until `exp`. If there is no `nbf` claim, then there there are two options:
- The system pretends that `nbf` is set to `0`, so the token will be usable until `exp`.
- The system uses the `iat` claim that specifies the timestamp that the token was issued. Although it's reasonable to not accept tokens before they were actually issued, this is not in [the standard](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6).

The `iat` should the exact timestamp (of the server that issues the token). Both `nbf` and `exp` can be set by the IDP to any timestamp that seems appropriate.

Time differences between servers is generally not an issue for token expiration. Most clients will renew tokens well before they expire, so the time deviation won't result in any issues. The problem is mostly when the server issuing tokens is set to a later timestamp then the server that consumes (and validates) the token.

The cleanest method is to ensure that the token issuer sets `nbf` 5 minutes _before_ the `iat` timestamp. This will allow a 5 minute time deviation between the issuing and consuming server. Unfortunately, not all OIDC servers allow to set the `nbf` claim.

Some other clients allow some time to deal with time deviation between servers. They allow a token to be used _N_ seconds before `nbf` (or maybe `iat`) and _N_ seconds after `exp`. Although the specification mentions "some time" (up to a few minutes) to deal with clock skewing, it may not meet everyone's security standards.
