### ISSUE TITLE
MINIO_BROWSER_REDIRECT_URL  Subpath not working

### ISSUE THREAD

**Issue by vmire** [minio/console#2774]
Some url generated by the console does not use subpath

Similar issue was resolved last year for download link ( #2272  ).
This subpath bug reappears in recent versions for bucket list.

Minio configured with :
MINIO_BROWSER_REDIRECT_URL: 'http://localhost:8080/minio/'

Generated API URL : 
http://localhost:8080/api/v1/buckets

instead of http://localhost:8080/minio/api/v1/buckets

**Comment by goganchic** [comment]
In [RELEASE.2023-03-22T06-36-24Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-03-22T06-36-24Z) all urls worked as expected, so it's broken in [RELEASE.2023-03-24T21-41-23Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-03-24T21-41-23Z) or [RELEASE.2023-04-07T05-28-58Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-04-07T05-28-58Z).

**Comment by cassidy3** [comment]
FWIW version 2023-03-24T21:41:23Z appears to be working for me, but I see the same issue with subpath redirect with any version newer than that.

**Comment by mskyttner** [comment]
After upgrading to latest (to get ftp/sftp) today and running into this issue, I was able to roll back to recover a working instance with a reverse proxied console UI (proxied by nginx, using `quay.io/minio/minio:RELEASE.2023-03-24T21-41-23Z`). 

Thanks for listing the latest stable version that doesn't break reverse-proxied instances @cassidy3 @goganchic, worth a lot!

**Comment by cassidy3** [comment]
FWIW I'm using HAProxy for subpath redirect. Same issue as the Nginx users here.

**Comment by itzsimpl** [comment]
Same thing with traefik; 2023-03-24T21:41:23Z seems to be the last working version.

**Comment by swoiow** [comment]
Hi all. Yes, actually i met the same issue too. And let me show more deatils about this issue.

- Nginx
- docker 
  - minio:latest tag with hash id (3067751629ce)
  - image label `"io.buildah.version": "1.27.3", "release": "RELEASE.2023-05-04T21-44-30Z",`

As same as vmire said,  i config the `MINIO_BROWSER_REDIRECT_URL ` in docker env, and also config the nginx, so that i want to mount minio under a domain with a subpath, just like vmire said.
But, the frontend not reference the `MINIO_BROWSER_REDIRECT_URL`, when call the api.

FYI, when i used another version too, that version is `2022-11-17T23:20:09Z`, that released was no this issue, and work fine.

**Comment by underscoredje** [comment]
Hi all.

Same here.
Tested with:
  * docker / nginx
  * k8s / traefik2

The last working version is 2023-03-24T21:41:23Z as @cassidy3 said.
