### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by FairyTail2000** [minio/console#3057]
I have created a user with the named "4,^AFzQ&w_6H"D?;_D<\/,Wd($m*k*gef^[VRm%o$g-fYUXBV^\`98v+#({sQRw?jhg.Ue*H#vs9nwB&"\~nHrkJ7q\`N#&7!?8Eu4:4!x~joSGmoL%y=oQ}U@/"yz3{g4" which is a kinda dump name I realized after creating it

## Expected Behavior
I should be able to delete it from the frontend

## Current Behavior
The frontend responds with "not found"
![image](https://github.com/minio/minio/assets/22645621/e892ed9a-91a4-43dc-b600-bb70a8b22db7)

## Steps to Reproduce (for bugs)

1. Create a user with given name
2. Try to delete it
3. Profit

## Regression
No

## Your Environment

minio version RELEASE.2023-09-16T01-01-47Z (commit-id=b733e6e83cee28820e815787b0562d17b14f9759)
Runtime: go1.21.1 linux/amd64

* Server setup and configuration: Not applicable
* Operating System and version (`uname -a`): Linux <> 5.10.0-21-cloud-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Comment by FairyTail2000** [comment]
Filesystem:
![image](https://github.com/minio/console/assets/22645621/6034d53b-bc18-4315-9c9d-23c975c976f0)

**Comment by FairyTail2000** [comment]
It looks like the / characters inside is breaking the path building, but I can be wrong

**Comment by ramondeklein** [comment]
The actual problem is that base64 encoding is used to encode the username, but standard base64 encoding is not URL-safe. To use URL-safe encoding, you should use `base64.URLEncoding` instead of `base64.StdEncoding`. However, it's not needed to encode the parameters, because Javascript already provides the [`encodeURIComponent(...)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) function to encode text. The advantage is that the Go server automatically decodes the parameters without needing to call any functions. Also URLs look a bit more correct.
