### ISSUE TITLE
GUI: create default policies to access the new bucket?

### ISSUE THREAD

**Issue by harridu** [minio/console#3218]
Being new to S3 and minio its easy to create new buckets and add new users in the GUI and to get something running quickly, but it is rather complex to create policies in the GUI. Having good policies is key to minio. Sorry to say, but the Web GUI is not very helpful here. Result: A few buckets accessible to everybody with an account. Next project is pressing. Thats bad.

Would it be possible to optionally add dedicated readonly and readwrite policies on creating a new bucket in the GUI? A checkbox maybe?

**Comment by prakashsvmx** [comment]
There are built in policies.  It just needs to be associated with group or users .  

S3 API does not specify policies for a bucket (only anonymous policies can be set at bucket level after creating the bucket. )

New users do not have default policies. https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-user-add.html#id7

https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#id3


The above request looks like application specific which could be achieved with may be an automated bucket /user provisioning script. 

Unfortunately application specific use cases would not be implemented or supported upstream unless otherwise it solves a majority of use cases.
