### ISSUE TITLE
wrong mime on Windows

### ISSUE THREAD

**Issue by niphlod** [minio/console#802]
Started minio as

```
SET MINIO_REGION=eu-west-1
SET MINIO_ROOT_USER=foo
SET MINIO_ROOT_PASSWORD=bar

minio.exe server --address :3000 "C:\some\folder"
```

Started console as
```
set CONSOLE_PBKDF_PASSPHRASE=something
set CONSOLE_PBKDF_SALT=difficult
set CONSOLE_MINIO_SERVER=http://127.0.0.1:3000

console-windows-amd64.exe server
```

When running on windows, browser reports this

Refused to execute script from 'http://127.0.0.1:9090/static/js/2.59d83018.chunk.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

As result, you get a blank page when trying to connect to http://127.0.0.1:9090

What am I doing wrong ?

**Comment by bexsoft** [comment]
Hi!

Thank you for your message, what version of console are you running?

**Comment by niphlod** [comment]
VERSION:
  0.7.4 - 16647b88

**Comment by uhfath** [comment]
Same here.
Chrome 91.0.4472.124

**Comment by bexsoft** [comment]
Hi! 

There is a reported issue with golang & windows, on which MIME types can be changed by some applications and return non-valid MIME types: https://github.com/golang/go/issues/32350. This issue is exclusive for Windows OS and doesn't apply for Linux / Apple users

As a temporal fix, you may want to try to insert the following keys in windows registry:

```
[HKEY_CLASSES_ROOT\.js]
"Content Type"="text/javascript"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.js]
"Content Type"="text/javascript"
```

Please let us know if you find any other issue, we will be happy to help!

**Comment by niphlod** [comment]
confirmed, fixing the registry worked. 
@harshavardhana : Sorry for forgotting to update this in the first place, you can close this.

**Comment by bexsoft** [comment]
Applied a WA in https://github.com/minio/console/pull/1014, Will be ready in version 0.9.8
